---
abstract: 'Collaborative, content-based spam filtering network agent.'
author:
  - 'Vipul Ved Prakash <mail@vipul.net>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.24, CPAN::Meta::Converter version 2.150010'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Razor2-Client-Agent
no_index:
  directory:
    - t
    - inc
requires:
  Digest::SHA: '0'
  File::Copy: '0'
  File::Spec: '0'
  Getopt::Long: '0'
  MIME::Base64: '0'
  Test::More: '0'
  Time::HiRes: '0'
  URI::Escape: '0'
resources:
  MailingList: https://sourceforge.net/mailarchive/forum.php?forum_name=razor-users
  bugtracker: http://sourceforge.net/projects/razor
  homepage: http://razor.sourceforge.net/
  license: http://dev.perl.org/licenses/
  repository: http://github.com/toddr/Razor2-Client-Agent
version: '2.86'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
